# -*- coding: utf-8 -*-
"""7 Numpy_image_creation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ku0_WvhFvh-SSxKY2hu6nf3i5hfSfPd2
"""

import numpy as np
import matplotlib.pyplot as plt


image = np.zeros((100, 100, 3), dtype=np.uint8)


center = (50, 50)
radius = 40
image[center[1]-radius:center[1]+radius, center[0]-radius:center[0]+radius] = [255, 255, 0]


left_eye_center = (35, 35)
right_eye_center = (65, 35)
eye_radius = 5
image[left_eye_center[1]-eye_radius:left_eye_center[1]+eye_radius,
      left_eye_center[0]-eye_radius:left_eye_center[0]+eye_radius] = [0, 0, 0]
image[right_eye_center[1]-eye_radius:right_eye_center[1]+eye_radius,
      right_eye_center[0]-eye_radius:right_eye_center[0]+eye_radius] = [0, 0, 0]

smile_center = (50, 50)
smile_radius = 25
start_angle = np.deg2rad(30)
end_angle = np.deg2rad(150)
line_thickness = 2
for angle in np.linspace(start_angle, end_angle, 100):
    x = smile_center[0] + smile_radius * np.cos(angle)
    y = smile_center[1] + smile_radius * np.sin(angle)
    image[int(y):int(y)+line_thickness, int(x)-line_thickness:int(x)+line_thickness] = [0, 0, 0]


plt.imshow(image)
plt.axis('off')
plt.show()